version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "black"

[[transformers]]
name = "ruff"

[[transformers]]
name = "isort"

[[transformers]]
name = "yapf"

[[transformers]]
name = "autopep8"